<a href="https://colab.research.google.com/github/jcj217-mc/Data_205/blob/main/Keith_Galli_NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Load in NumPy (remember to pip install numpy first)**

In [ ]:
import numpy as np

## **The Basics**

In [ ]:
a = np.array ([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9, 8, 7], [6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
# Get Total size
a.nbytes

12

In [ ]:
# get number of elements
a.size

3

## **Accessing/Changing specific elements, rows, columns, etc.**

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c] - row, column
a[1,5]

13

In [ ]:
# get a specific row - row listed, column ":" for all columns
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column - row ":" for all rows, column listed
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:step size]
# 0,1 - start index, -1 end index, 2 step size
a[0,1 :-1 :2]

array([2, 4, 6])

In [ ]:
# Changing item by index
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
#3D example
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
# b[set, row, column]
b[0,1,1]

4

In [ ]:
# replace
# b[set, row, column] - all sets, second row, all columns
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


##**Initializing Different Types of Arrays**

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix - set, row, column - can specify data type but do not have to
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# 4D example - two mega sets, 3 sets within the megasets, 3 rows and 2 columns within each set
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
# Any other number - np.full((# rows, # columns), number)
# shape is (2,2), value is 99
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number - np.full((# rows, # columns), number)
# shape is (2,2), value is 99
# can add datatype
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full_like)
# take a shape that is already built and reuse it with a differet value or set of values but that has the same size
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# another way to do full_like is 
# take a shape that is already built and reuse it with a differet value or set of values but that has the same size
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
# specify shape, here it is (4,2) - 4 rows, 2 columns
np.random.rand(4,2)

array([[0.75469474, 0.23563662],
       [0.37027973, 0.39785099],
       [0.37904512, 0.64479033],
       [0.36950958, 0.95473785]])

In [ ]:
# Random decimal numbers
# specify shape, here it is (4,2,3) - 4 sets, 2 rows, 3 columns
np.random.rand(4,2,3)

array([[[0.34077278, 0.71269508, 0.1685989 ],
        [0.22785658, 0.53640656, 0.70288547]],

       [[0.38079988, 0.69862417, 0.38090779],
        [0.57276743, 0.37626459, 0.54925895]],

       [[0.17604417, 0.78772835, 0.63174787],
        [0.42091555, 0.37403931, 0.93184304]],

       [[0.91917539, 0.22270216, 0.81313671],
        [0.1214064 , 0.47188935, 0.84414728]]])

In [ ]:
# random sample same shape as above
np.random.random_sample(a.shape)

array([[0.83644894, 0.45021779, 0.69764201, 0.29000583, 0.815465  ,
        0.7005419 , 0.74032195],
       [0.17447898, 0.20967075, 0.4808016 , 0.58570006, 0.4084753 ,
        0.9460554 , 0.96211279]])

In [ ]:
# Random integers - no decimals
# specify start value
# 7 numbers up to 7, shape listed as "size" - 3 rows, 3 columns
np.random.randint(7, size=(3,3))

array([[5, 6, 0],
       [1, 0, 6],
       [5, 5, 2]])

In [ ]:
# more examples
# from 4 to 7 with 3 rows and 3 columns
# 7 is exclusive
# can include negative numbers
np.random.randint(4,7, size=(3,3))

array([[6, 6, 5],
       [4, 4, 4],
       [5, 5, 6]])

In [ ]:
# can include negative numbers
np.random.randint(-4,8, size=(3,3))

array([[-4,  2,  7],
       [ 0,  2,  4],
       [-4,  6,  1]])

In [ ]:
# Identity Matrix
# 3 rows, 3 columns
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Identity Matrix
# Identity Matrix must be same number of R and C - Square Matrix by it's nature
# 3 rows, 3 columns
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Repeat an array a few times
arr = np.array([1,2,3])
# repeat array 3 times
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# Repeat an array a few times
# Make it two dimensional
arr = np.array([[1,2,3]])
# repeat array 3 times, the axis = 0 makes separate rows for each set
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Repeat an array a few times
# Make it two dimensional
arr = np.array([[1,2,3]])
# repeat array 3 times, the axis = 1 makes it all in one row
r1 = np.repeat(arr, 3, axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# Try to recreate picture that looks like
# 11111
# 10001
# 10901
# 10001
# 11111


In [ ]:
# exercise my solution
array = np.ones((5,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# changing center position to 9
array[2,2] = 9
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# changing square positions to 0
array[1,1:4] = 0
array[2,1] = 0
array[2,3] = 0
array[3, 1:4]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# exercise his solution
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
# replace middle part with z
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## **Be careful when copying arrays!!**

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)
# a changed as well when b was changed!!!

# it is the if change a, b changes
a[2] = 5
print(a)
print(b)

[100   2   3]
[100   2   3]
[100   2   5]
[100   2   5]


In [ ]:
# Instead use copy() - it copies the content to make b
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


##**Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# 2 plus everything
a += 2
print(a)

[3 4 5 6]


In [ ]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## **Linear Algebra - often Matlab**

In [ ]:
# element wise computation 
# a * b

In [ ]:
# 2 by 3 matrix of ones
a = np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

# Linear alebra must have columns of first matrix equal to rows of second one

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# should end up with 2 x 2 with multiplication
# matrix multiplication function 
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [ ]:
# determinant of a matrix
# identity matrix has a determinant of 1
c = np.identity(3)
np.linalg.det(c)


1.0

In [ ]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## **Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
# min of first and second row - min by row is axis = 1
np.min(stats, axis = 1)

array([1, 4])

In [ ]:
# min of each column, axis = 0
np.min(stats, axis = 0)

array([1, 2, 3])

In [ ]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [ ]:
np.max(stats, axis = 1)

array([3, 6])

In [ ]:
# sums all items in matrix
np.sum(stats)

21

In [ ]:
# sums all items in each row
np.sum(stats, axis = 1)

array([ 6, 15])

In [ ]:
# sums all items in each column
np.sum(stats, axis = 0)

array([5, 7, 9])

## **Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print(before.shape)

(2, 4)


In [ ]:
# make it a 8 x 1
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# make it 4 x 2
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# make it 2 x 2 x 2
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# vertically stacking vectors or matrices
# dimensions important
v1 = np.array([1,2,3,4,])
v2 = np.array([5,6,7,8])

# stack v1 on top of v2 as part of same matrix
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# can keep passing in - can weave in different orders
# sizes must be the same
np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
# horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
# horizonatl stack
# stacked the h2 to the right of h1
np.hstack((h1,h2))

##**Miscellaneous**
####*Load Data from File*

In [ ]:
# load with numpy array instead of pandas
# delimiter is a separator meaning separate with a comma
# np.genfromtext('name of file.txt', delimiter=',')

#### **Boolean Masking and Advanced Indexing**

In [ ]:
# where in filedata are entries > 50
# Gives T, F boolean outcome

In [ ]:
# grab only values with value >50
data[data > 50]

In [ ]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
# a[[True]]

In [ ]:
# If any value > 50
# np.any(filedata > 50, axis=0)
# if look downward are any of the values >50

In [ ]:
# Column entries > 50
# np.all(filedata > 50, axis=0)

In [ ]:
# Row entries > 50
# np.all(filedata > 50, axis=1)

In [ ]:
# multiple conditions
# greater than 50 and less than 100
# ((filedata > 50 & filedata < 100))

In [ ]:
# not (greater than 50 and less than 100)
# inverse of above
# (~((file>50) & (file<100)))

In [ ]:
m = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# choose 11, 12, 16, 17

array([11])

In [ ]:
m[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
# choose 2, 8, 14, and 20
# need to use two different lists within your indexing
m[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
# index 4,5,24,25,29,30
# my try: m[[1,3:5],[4:6,3:5]]
# answer:
m[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])